### ISSUE TITLE
Fade Animation

### ISSUE THREAD

**Issue by lucsoft** [Minenash/Seamless-Loading-Screen#2]
Add a fade animation when switching from Image to World

**Comment by Minenash** [comment]
Okay, so I finally got the fade working. Not 100% how I like it, and I'm not really sure what the default length should be. It also doesn't help that the player can move the camera (which I might try to stop?). Tomorrow I'll push a beta build that has the fade with a config allowing to change the duration of it and (hopefully) the option to stop the player from moving the camera until the fade is complete (or almost done)

**Comment by SemmieboyYT** [comment]
I also have an idea for a transition. Why don't you try to make it so when a player joins a world/server you will make it so the client does not send movement updates and keeps the loading screen open, until some chunks around the player are loaded (maybe just the nine chunks around the player, or fancier the chunks the player is looking at). Then you make the client send movement updates again and close the loading screen so that the world is a bit preloaded before closing the screen wich will prevent seeing the big void of nothing before the world loads.

**Comment by Minenash** [comment]
Added in v1.1.0-beta.1

I did disable camera movement, since that's the easiest to accidentally move. I could also add movement block, but it would probably be off be default
