### ISSUE TITLE
If Nether ambience plays, it will not stop when returning to the overworld

### ISSUE THREAD

**Issue by Crystalwarrior** [Minenash/Seamless-Loading-Screen#20]
This happens on Fabric API 0.30, Seamless Loading Screen 1.2.2
I have identified this mod to be the culprit behind this bug, as it doesn't happen on vanilla or without this mod enabled.
Seems like travelling between nether/overworld somehow has this plugin break the ambience, making it not stop when you leave the Nether.

**Comment by Minenash** [comment]
I can't find anything that would cause this, but I'll look a bit deeper tomorrow

**Comment by Minenash** [comment]
Oh, I'm dumb. One of the screen's I override/replace was the joining world screen. Since that screen is used both both initial join (when I want it to show) and changing worlds (overworld -> nether, etc), I checked to see if it was the initial one. I did this by replacing the reset call (which changes screens, resets the audio, etc) with custom code that resets it with the the custom screen. The problem was that if it wasn't where I wanted to replace it, the code got replaced with nothing, so it never called reset, which meant the audio was never reset. This is now fixed and will be in the v1.3.0 release today. (or v1.3.0-beta.1 if I can't get the translations in time)

**Comment by Crystalwarrior** [comment]
> 
> 
> Oh, I'm dumb. One of the screen's I override/replace was the joining world screen. Since that screen is used both both initial join (when I want it to show) and changing worlds (overworld -> nether, etc), I checked to see if it was the initial one. I did this by replacing the reset call (which changes screens, resets the audio, etc) with custom code that resets it with the the custom screen. The problem was that if it wasn't where I wanted to replace it (i.e. changing dimensions), the code got replaced with nothing, so it never called reset, which meant the audio was never reset. This is now fixed and will be in the v1.3.0 release today. (or v1.3.0-beta.1 if I can't get the translations in time)

LOOOL this is amazing, yeah I was wondering it was smth like that cuz I could've sworn there's a loading screen between dimensions

**Comment by Minenash** [comment]
Fixed in v1.3.0 and v1.3.1
