### ISSUE TITLE
Saving a world with the F3 menu results in weirdly moved F3 menu on the screenshot.

### ISSUE THREAD

**Issue by RDKRACZ** [Minenash/Seamless-Loading-Screen#28]
![image](https://user-images.githubusercontent.com/43277609/110628103-034d9300-81a3-11eb-8851-24d1ceed4c57.png)

**Comment by HackerPide** [comment]
I think this is due to the resolution setting. Try using 'Native' if you aren't already.

**Comment by Minenash** [comment]
Apparently Mojang itself doesn't follow the hudhidden option when it comes to the debug menu... nice. To fix this I would need to make it so that it does respect it, which shouldn't be too hard.

If the resolution was changed to Native, it would just show at a more normal scale, it would still be there though.

**Comment by Minenash** [comment]
Fixed in v1.3.3
