### ISSUE TITLE
Incompatible with Automodpack 

### ISSUE THREAD

**Issue by Toon2400** [Minenash/Seamless-Loading-Screen#66]
Whenever [automodpack ](https://github.com/Skidamek/AutoModpack) pops up asking the user if they would like to download/restart the client after joining the server, all game input is disabled and no buttons can be clicked what-so-ever

_If you know a fix that could be implemented into the other mod let me know and i'll forward it to the mod creator if you'd like_

**Comment by SlayerTheChikken** [comment]
This is probably related to the same problem so I'm just going to add that it does the same thing with the Origins mod, exiting and saving then going back into a new world causes the buttons to do nothing or even have a hover animation.

**Comment by SlayerTheChikken** [comment]
How to trigger bug (easily:)
Create a new world with default everything, save and exit, delete the world you just made, make a new world with default everything, origins menu non functional. 

Why? Because seamless loading screen disables input until it detects the world as loaded, except a popup prevents that so input is not restored.

Fix? You can change "disableCamera" to false to prevent input from being disabled, this breaks other things however when you leave the game again (probably because it thinks the world never loaded,) for example fancy menu (see below.)

![image](https://github.com/Minenash/Seamless-Loading-Screen/assets/20819543/b4f5cd3c-cd92-44a4-b794-04ca20a5cdf1)

**Comment by Dragon-Seeker** [comment]
> How to trigger bug (easily:) Create a new world with default everything, save and exit, delete the world you just made, make a new world with default everything, origins menu non functional.
> 
> Why? Because seamless loading screen disables input until it detects the world as loaded, except a popup prevents that so input is not restored.
> 
> Fix? You can change "disableCamera" to false to prevent input from being disabled, this breaks other things however when you leave the game again (probably because it thinks the world never loaded,) for example fancy menu (see below.)
> 
> ![image](https://user-images.githubusercontent.com/20819543/263841516-b4f5cd3c-cd92-44a4-b794-04ca20a5cdf1.png)

I would recommend that you make a new issue next time and could you try with the latest release of the mod?

**Comment by SlayerTheChikken** [comment]
No change with the latest version for me, must be a different issue, I will make a new one I am sorry
